### ISSUE TITLE
Potential Bug

### ISSUE THREAD

**Issue by MaifengNg** [AY2122S1-CS2113-T14-1/tp#231]
<img width="612" alt="image" src="https://user-images.githubusercontent.com/75520172/140450533-0d5b5ffb-e6e5-41c0-83db-dc4d2550696e.png">

/note command does not handle /back or rather it treats /back as a wrong command.

**Comment by peng-217** [comment]
Because this /back command is not supported in note function, to go back to previous scene, you need to type "/quit" to quit note process, then type "/back" to go back to previous scene.
